# Use the official PHP 8.3 image as the base image
FROM php:8.3-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    cron \
    supervisor \
    openssl \
    sudo \
    libonig-dev \
    libxml2-dev \
    libssl-dev \
    pkg-config \
    libcurl4-openssl-dev \
    libedit-dev \
    libsqlite3-dev \
    libssl-dev \
    libicu-dev \
    libpq-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libz-dev \
    default-mysql-client \
    libmagickwand-dev --no-install-recommends

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli pdo pdo_mysql mbstring exif pcntl bcmath gd intl zip opcache

# Install Redis extension
RUN pecl install redis \
    && docker-php-ext-enable redis

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory contents
COPY . /var/www/html

# Remove vendor directory
# RUN rm -rf /var/www/html/vendor

# Run composer install
RUN composer install

# custom php.ini file
ADD docker/php/custom-php.ini /usr/local/etc/php/conf.d/custom-php.ini

# Add custom PHP-FPM configuration
ADD docker/php/custom-php-fpm.conf /usr/local/etc/php-fpm.d/custom-php-fpm.conf


# Expose port 9000 and start php-fpm server
EXPOSE 9000
EXPOSE 8000
EXPOSE 8080
EXPOSE 3307
EXPOSE 80
